name: MyPy

on: [push, pull_request, workflow_dispatch]

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python V3.11 and Cache
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mypy --install-types --non-interactive

      - name: Set default environment variables
        run: |
          echo "mypy_warnings=INVALID" >> $GITHUB_ENV

      - name: Run type checker
        run: |
          mypy main.py src | tee mypy_output.txt
          MYPY_WARNINGS=$(grep -oP '\b\d+(?= errors?)|\bno issues found\b' mypy_output.txt | tail -n1 | sed 's/\bno issues found\b/0/')
          echo "mypy_warnings=${MYPY_WARNINGS}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Create mypy warning badge
        if: ${{ github.ref_name == 'main' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 328c50761ab662216df5dfb1debb334a
          filename: mypy_warnings.json
          label: MyPy Warnings
          labelColor: "#1e1e2e"
          namedLogo: typescript
          style: flat
          message: ${{ env.mypy_warnings }}
          valColorRange: ${{ env.mypy_warnings }}
          minColorRange: 1
          maxColorRange: 6
          invertColorRange: true
