name: Python CI Example

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python V3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set default environment variables
      run: |
        echo "pylint_score=INVALID" >> $GITHUB_ENV

    - name: Run static code analysis
      run: |
        pylint --output-format=parseable main.py source tests | tee pylint_output.txt
        PYLINT_SCORE=$(grep -oP 'Your code has been rated at \K[^/]+' pylint_output.txt)
        echo "pylint_score=${PYLINT_SCORE}" >> $GITHUB_ENV
      continue-on-error: true

    - name: Create pylint badge
      if: ${{ github.ref_name == 'main' }}
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 328c50761ab662216df5dfb1debb334a
        filename: pylint-score.json
        label: Pylint Score
        message: ${{ env.pylint_score }}
        valColorRange: ${{ env.pylint_score }}
        minColorRange: 5
        maxColorRange: 9
